# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

name = 'TestPods'
branch_chat = 'v4'
branch_video = 'develop'
github = 'https://github.com/GetStream'

workspace name

target name do
  project "#{name}.xcodeproj"
  pod 'StreamVideo', :git => "#{github}/stream-video-swift.git", :branch => branch_video
  pod 'StreamVideoSwiftUI', :git => "#{github}/stream-video-swift.git", :branch => branch_video
  pod 'StreamVideoUIKit', :git => "#{github}/stream-video-swift.git", :branch => branch_video
end
