default_platform :ios
skip_docs

before_all do
  if is_ci
    setup_ci
    setup_git_config
    select_xcode(version: '26.2')
  end
end

lane :test do |options|
  test_spm(options)
end

lane :test_spm do |options|
  gym(
    project: "#{options[:project]}/#{options[:project]}.xcodeproj",
    scheme: options[:project],
    configuration: 'Release',
    skip_codesigning: true,
    skip_archive: true,
    clean: true
  )
end

lane :switch_chat_spm_branch do |options|
  branch = options[:branch] || UI.user_error!('Branch is required')

  project = options[:project] || UI.user_error!('Project is required')
  UI.message("[#{project}] Setting up Chat SPM branches to #{branch}")
  pbxproj_path = File.expand_path("../#{project}/#{project}.xcodeproj/project.pbxproj")
  content = File.read(pbxproj_path)
  content.gsub!(/(XCRemoteSwiftPackageReference "stream-chat-swift"[^}]*branch = )develop(;)/m, "\\1#{branch}\\2")
  content.gsub!(/(XCRemoteSwiftPackageReference "stream-chat-swiftui"[^}]*branch = )develop(;)/m, "\\1#{branch}\\2")
  File.write(pbxproj_path, content)
  UI.success("[#{project}] Chat SPM branches set to #{branch}")
end
